config/routes.rb
Rails.application.routes.draw do

  get 'shop_sessions/new'

  get 'shops/new'

  get 'cars/new'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'shophome' => 'static_pages#shop_home', as:"shop_home"
  get 'shop', to: 'static_pages#shop_home', as: 'shop_root'
  get 'shops', to: 'shops#index', as: 'shop_index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'shopsignup' => 'shops#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'shoplogin'   => 'shop_sessions#new', as: 'shop_login'
  post   'shoplogin'   => 'shop_sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'shoplogout'  => 'shop_sessions#destroy', as: 'shop_logout'
  post 'updateshop' => 'users#update_shop', as: 'update_shop'
  get 'customers' => 'shops#customers'
  resources :shops do 
    get 'customers', on: :member 
  end
  
  resources :users
  resources :cars,  only: [:create, :destroy, :edit]
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :users
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  mount_uploader :picture, ShoppicUploader
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :city, presence: true, length: { maximum: 30 }
  validates :state, presence: true, length: { maximum: 2 }
  validates :zip, presence: true, length: { maximum: 5 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :phone, presence: true, length: { maximum: 15 }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true
  
  def Shop.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = Shop.new_token
    update_attribute(:remember_digest, Shop.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :logged_in_shop, only: [:edit, :update]
  before_action :logged_in_user, only: :destroy
  before_action :correct_shop, only: [:edit, :update]
  before_action :admin_user,     only: :destroy
     
    def index
      @shops = Shop.all
    end
    
    def show
      @shop = Shop.find(params[:id])
      @user = current_user
    end
    
    def new
      @shop = Shop.new
    end
    
    def create
      @shop = Shop.new(shop_params)
      if @shop.save
        shop_log_in @shop
        flash[:success] = "Thank you for signing up, welcome to Ensage!"
        redirect_to shop_home_path
      else
        render 'new'
      end
    end
    
    def edit
      @shop = Shop.find(params[:id])
    end

    def update
      @shop = Shop.find(params[:id])
      if @shop.update_attributes(shop_params)
        flash[:success] = "Profile Updated"
        redirect_to @shop
      else
          render 'edit'
      end
    end
    
    def destroy
      Shop.find(params[:id]).destroy
      flash[:success] = "Shop Deleted"
      redirect_to shops_url
    end

    def customers
      @shop = current_shop
      @customers = @shop.users
    end
    
    private

    def shop_params
      params.require(:shop).permit(:name, :address, :city, :state, :zip, :email, :phone, :password,
                                   :password_confirmation, :picture)
    end
    
    def correct_shop
      @shop = Shop.find(params[:id])
      redirect_to(root_url) unless current_shop?(@shop)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_shop.html.erb
<h1> <%= @shop.name %> </h1>
<div class="center hero-unit col-md-8 col-md-offset-2" id="shop">
  <div class="shop_pic">
    <%= image_tag @shop.picture.url if @shop.picture? %>
  </div>
  <% if logged_in? && @user.shop_id.nil? %>
    <%= link_to 'Add As Your Shop', update_shop_url(id: @user.id, shop_id: @shop.id), class: 'blue-button', data: { method: 'post' } %>
  <% end %>
  <% if logged_in? && !@user.shop_id.nil? && @user.shop_id != @shop.id %>
    <%= link_to 'Switch To This Shop', update_shop_url(id: @user.id, shop_id: @shop.id), class: 'blue-button', data: { method: 'post' } %>
  <% end %>
  <div class="shop-info">
    <h2>Location</h2>
    <h3>
      <%= @shop.address %>, <%= @shop.city %>, <%= @shop.state %>, 
      <%= @shop.zip %>
    </h3>
    <h2>Contact</h2>
    <h3>
      <%= @shop.email %>, <%= @shop.phone %>
    </h3>
  </div>
</div>

app/views/shops/customers.html.erb
<div id="customers_feed">
    <% if @customers.any? %>
      <ul class="customers">
        <%= render @customers %>
      </ul>
    <% else %>
      <h3> No customers have added you as their designated shop yet.</h3>
    <% end %>
</div>

app/views/shops/edit.html.erb
<% provide(:title, "Edit Account") %>
<h1>Update your business profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@shop) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
      
      <%= f.label :zip %>
      <%= f.text_field :zip, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Your Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shops/index.html.erb
<% provide(:title, 'All shops') %>
<h1>All Garages</h1>

<ul class="center hero-unit col-md-6 col-md-offset-3 shops">
  <% @shops.each do |shop| %>
    <li>
      <div class= "shop-name pull-left">
      <%= link_to shop.name, shop %>
        <% if current_user.admin? && !current_shop?(shop) %>
        | <%= link_to "(Delete Shop)", shop, method: :delete,
                                      data: { confirm: "You sure?" } %>
        <% end %>
      </div>
      <div class= "shop-address pull-right">
      <p><%= shop.address %> <br> <%= shop.city %>, <%= shop.state %> <%= shop.zip %> <br> <%= shop.phone %></p>
      </div>
    </li>
  <% end %>
</ul>

app/views/shops/new.html.erb
<% provide(:title, 'Business Sign up') %>
<div class="signup-head">
  <h1>Business Signup</h1>
  <h2> Are you registering as a driver? <%= link_to "Sign up Here", signup_path %> </h2> 
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <%= form_for(@shop, html: { multipart: true}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Business Name" %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :address, "Address" %>
      <%= f.text_field :address, class: 'form-control' %>
      
      <%= f.label :city, "City" %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state, "State" %>
      <%= f.text_field :state, class: 'form-control' %>
      
      <%= f.label :zip, "ZIP Code" %>
      <%= f.text_field :zip, class: 'form-control' %>
      
      <%= f.label :email, "Email Address" %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone, "Phone Number" %>
      <%= f.telephone_field :phone, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Your Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <h3> Add a photo of your business </h3>
      <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      
      <%= f.submit "Create business account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#shop_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shops/show.html.erb
<% provide(:title, @shop.name) %>

<div>
  <%= render 'shops/shop' %>
</div>