config/routes.rb
Rails.application.routes.draw do

  get 'shop_sessions/new'

  get 'shops/new'

  get 'cars/new'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'shophome' => 'static_pages#shop_home', as:"shop_home"
  get 'shop', to: 'static_pages#shop_home', as: 'shop_root'
  get 'shops', to: 'shops#index', as: 'shop_index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'shopsignup' => 'shops#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'shoplogin'   => 'shop_sessions#new', as: 'shop_login'
  post   'shoplogin'   => 'shop_sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'shoplogout'  => 'shop_sessions#destroy', as: 'shop_logout'
  post 'updateshop' => 'users#update_shop', as: 'update_shop'
  get 'customers' => 'shops#customers'
  resources :shops do 
    get 'customers', on: :member 
  end
  
  resources :users
  resources :cars,  only: [:create, :destroy, :edit]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cars, :dependent => :delete_all
  belongs_to :shop
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :phone, presence:true
  validates :password, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def feed
    Car.where("user_id = ?", id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
    def index
      @users = User.all
    end
    
    def show
      @user = User.find(params[:id])
      @feed_items = @user.feed.paginate(page: params[:page])
    end
    
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Thank you for signing up, welcome to ensage!"
        redirect_to root_path
      else
        render 'new'
      end
    end
    
    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
          render 'edit'
      end
    end

    def update_shop
      @user = User.find(params[:id])
      @shop = Shop.find(params[:shop_id])
      @user.update_attributes(shop_id: @shop.id)
      flash[:success] = "Added Shop!"
      redirect_to @shop
    end
    
    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end
    
    private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :password,
                                   :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div>
  <aside class="col-md-4">
    <div>
    </div>
    <div class="hero-unit user_info">
      <h1><%= link_to user.name, user%></h1>
      <h2><%= pluralize(user.cars.count, "Car") %></h2>
    </div>
  </aside>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Edit your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All drivers') %>
<h1>All Drivers</h1>

<ul class="center hero-unit col-md-6 col-md-offset-3 users">
  <% @users.each do |user| %>
    <div class="user-name">
    <li><%= link_to user.name, user %>
      <% if logged_in? %>
        <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to "(Delete User)", user, method: :delete,
                                        data: { confirm: "You sure?" } %></li>
        <% end %>
      <% end %>
    </div>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'User Sign up') %>
<div class="signup-head">
  <h1>Driver Sign up</h1>
  <h2> Are you registering for a business? <%= link_to "Sign up Here", shopsignup_path %> </h2> 
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Your Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
  <aside class="col-md-4">
    <div>
      <h1>My Profile</h1>
    </div>
    <div class="hero-unit user_info">
      <h1><%= @user.name %></h1>
      <h2><%= pluralize(@user.cars.count, "Car") %></h2>
    </div>
  </aside>
  
  <div class="col-md-8">
    <h1>My Cars</h1>
  </div>
  <div class="col-md-8">
    <%= render 'shared/feed' %>
  </div>
</div>