config/routes.rb
Rails.application.routes.draw do

  get 'shop_sessions/new'

  get 'shops/new'

  get 'cars/new'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'shophome' => 'static_pages#shop_home', as:"shop_home"
  get 'shop', to: 'static_pages#shop_home', as: 'shop_root'
  get 'shops', to: 'shops#index', as: 'shop_index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'shopsignup' => 'shops#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'shoplogin'   => 'shop_sessions#new', as: 'shop_login'
  post   'shoplogin'   => 'shop_sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'shoplogout'  => 'shop_sessions#destroy', as: 'shop_logout'
  post 'updateshop' => 'users#update_shop', as: 'update_shop'
  get 'customers' => 'shops#customers'
  resources :shops do 
    get 'customers', on: :member 
  end
  
  resources :users
  resources :cars,  only: [:create, :destroy, :edit]
end

app/views/shared/_car_form.html.erb
<%= form_for(@car, html: {multipart: true, remote: true}) do |f| %>
  <h3> Add Your Car</h3>
  <div class="field">
    <%= f.text_area :year, placeholder: "Year i.e. '1993" %>
    <%= f.text_area :brand, placeholder: "Brand i.e. 'Ford'"%>
    <%= f.text_area :model, placeholder: "Model i.e. 'Mustang'" %>
    <%= f.text_area :vin, placeholder: "17 digit VIN number" %>
    <%= f.text_area :mileage, placeholder: "Current Car Mileage" %>
  </div>
  <p> Add a Photo </p>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <div id="error_messages">
  </div>
  <%= f.submit "Add Car", class: "btn btn-add btn-primary" %>
  <button class="btn btn-hide btn-primary"> Hide Form </button>
  <% end %>
 
<script type="text/javascript">
  $('#car_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
      <h5>The form contains <%= pluralize(object.errors.count, "error") %>.</h5>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<div id="car_feed">
    <% if @feed_items %>
      <ul class="cars">
        <%= render @feed_items %>
      </ul>
    <% else %>
      <h3> You haven't added any cars yet.</h3>
      <h3> Add one in the sidebar!</h3>
    <% end %>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span> <%#= link_to "view my profile", root_path %></span>
<h2><%= pluralize(current_user.cars.count, "Car") %></h2>
<button class="btn btn-primary"> <%= link_to "Edit your profile", edit_user_path(current_user) %></button>
<button class="btn btn-primary">Add A Car</button>

app/views/shared/_user_signup.html.erb
  <%= form_for(@user.new) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :phone, "Phone Number" %>
    <%= f.telephone_field :phone, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirm Your Password" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>