config/routes.rb
Rails.application.routes.draw do

  get 'shop_sessions/new'

  get 'shops/new'

  get 'cars/new'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'shophome' => 'static_pages#shop_home', as:"shop_home"
  get 'shop', to: 'static_pages#shop_home', as: 'shop_root'
  get 'shops', to: 'shops#index', as: 'shop_index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'shopsignup' => 'shops#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'shoplogin'   => 'shop_sessions#new', as: 'shop_login'
  post   'shoplogin'   => 'shop_sessions#create'
  delete 'logout'  => 'sessions#destroy'
  delete 'shoplogout'  => 'shop_sessions#destroy', as: 'shop_logout'
  post 'updateshop' => 'users#update_shop', as: 'update_shop'
  get 'customers' => 'shops#customers'
  resources :shops do 
    get 'customers', on: :member 
  end
  
  resources :users
  resources :cars,  only: [:create, :destroy, :edit]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Born in WUSTL Hatchery
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Support/FAQs", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="logofont">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if shop_logged_in? %>
        <%= render 'layouts/shop_header' %>
        <% elsif logged_in? %>
        <%= render 'layouts/user_header' %>
        <% else %>
        <%= render 'layouts/login_options' %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_login_options.html.erb
<li  id="blacklink" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Login <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li id="blacklink"><%= link_to "For Drivers", login_path %></li>
    <li id="blacklink"><%= link_to "For Businesses", shop_login_path %></li>
    <li class="divider"></li>
  </ul>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_shop_header.html.erb
<% if shop_logged_in? %>
  <li id="blacklink"><%= link_to "Home", shop_home_path %></li>
  <li id="blacklink"><%= link_to "Drivers", users_path %></li> 
  <li id="blacklink"><%= link_to 'Customers', customers_shop_path(id: current_shop.id) %></li>
  <li id="blacklink"><%= link_to "Logout", shop_logout_path, method: "delete" %></li>  
<% end %>

app/views/layouts/_user_header.html.erb
<% if logged_in? %>
  <li id="blacklink"><%= link_to "Home", root_path %></li>
  <li id="blacklink"><%= link_to "Garages", shops_path %></li>
  <% if !current_user.shop_id.nil? %>
    <li id="blacklink"><%= link_to "My Garage", users_shop %></li>
  <% end %>
  <li id="blacklink"><%= link_to "Log out", logout_path, method: "delete" %></li>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="google-site-verification" content="Ehe3DsruRQGIAiIOKLENn_8AtV5pI6BUc32zHpnQguI" />
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
  <br><br><br><br><br>
  <%= debug(params) if Rails.env.development? %>
</html>